Bump aeson
snapframework/heist pull request #132
Opened 2021-12-24 06:13 UTC by soiamsoNG

Bump aeson to work with aeson 2.0 (default ordered KeyMap)
It also work with GHC 9.2.1 with configuration  allow-newer: all:all

2022-04-05 21:05 UTC, andreasabel commented on heist.cabal
> +    aeson                      >= 0.6     && < 3,
`<3` isn't a good upper bound.  Please change to `<2.1`.

2022-04-05 21:08 UTC, andreasabel requested changes

2022-04-05 21:08 UTC, andreasabel commented on src/Heist/Splices/Json.hs
> +        findIn (Object obj) = KM.lookup (K.fromText x) obj
This is the only line that is different and should be in the `#if`.  It seems superfluous to cut&paste the whole function.

2022-04-05 21:08 UTC, andreasabel commented on src/Heist/Splices/Json.hs
> +        let bindings = FI.ifoldl' bindKvp start  obj
There is ways to make the code `aeson-2` compatible with less duplication of code.

2022-04-06 13:37 UTC, andreasabel approved these changes
Excellent, thanks a lot @soiamsoNG !

2022-04-30 11:49 UTC, andreasabel commented
ping @mightybyte

2022-11-09 21:22 UTC, cydparser commented
Thanks!

2022-11-09 21:23 UTC, merged